on: pull_request
jobs:
  check-pr:
    name: validate commits
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.sha }}
        fetch-depth: 0
    - run: git fetch origin master
    - uses: flux-framework/pr-validator@master
  make-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: install dependencies
      run: >-
          sudo apt-get update -y &&
          sudo apt-get install -y enchant python3-pip &&
          sudo pip3 install --upgrade -r ./requirements.txt
    - name: make check
      run: make check
  make-linkcheck:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: install dependencies
      run: >-
          sudo apt-get update -y &&
          sudo apt-get install -y enchant python3-pip &&
          sudo pip3 install --upgrade -r ./requirements.txt
    - name: make linkcheck
      run: make linkcheck
